// Code generated by entc, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/Jeanhwea/baliqiao3/internal/app/mga/todo/todoadapter/ent/runtime.go

const (
	Version = "(devel)" // Version of ent codegen.
)
